module.exports = {
  pagesButton: "#nav-pages-button",
  pagesSearchbar: "//input[@data-testid='nav-pages-search']",
  pagesSearchBarText: "This Page Group",
  pageSearchResults: "//mark[text()='This Page Group']",
  pageTagsLabel: "//h2[text()='Page tags']",
  editMenu: "//unicon[@icon='edit']",
  pageSettingslabel: "//span[text()='Page settings']",
  managePagesMenu: "//span[text()='Manage pages']",
  managePagesTitle: "(//span[text()='Manage pages'])[2]",
  firstPageLabel: "(//div[contains(text(),'First Page')])[1]",
  pagesBurgerButton: "(//unicon[@class='ng-isolate-scope'])[10]",
  addSubPageOption: "//p[text()='Add sub-page']",
  addNavigationItem: "//span[text()='Add navigation item']",
  newPageButton: "(//span[@class='ng-scope'][normalize-space()='New page'])[1]",
  newLink: "(//span[normalize-space()='New link'])[1]",
  pageNameInput: "//input[@id='newPageModalInput']",
  newPageTitle: "//div[@class='fr-element fr-view']",
  pagesCreateButton: "button[type='submit'] span[class='ng-scope']",
  hoverFirstPage:
    "(//a[@name='First Page'][normalize-space()='First Page'])[1]",
};
